import { createServer, get, type Server } from 'node:http'
import { mkdtemp, readFile, rm, writeFile } from 'node:fs/promises'
import { tmpdir } from 'node:os'
import { join } from 'node:path'
import { once } from 'node:events'
import { createApp, createError, createRouter, defineEventHandler, getRouterParam, toNodeListener } from 'h3'
import { afterEach, beforeEach, describe, expect, it, vi } from 'vitest'
import { sendBackupFile } from '../../../server/utils/backups/download'
import { acquireSnapshotRead, snapshotHasReaders, reserveSnapshotDeletion } from '../../../server/utils/backups/snapshotReads'

const mocks = vi.hoisted(() => ({requireSuperadmin: vi.fn(), getBackup: vi.fn(), ensureBundle: vi.fn()}))
vi.mock('../../../server/utils/auth', () => mocks)
vi.mock('../../../server/utils/backups/registry', () => ({getBackup: mocks.getBackup, backupIdPart: (id: string) => id.replace(/^backups:/, '')}))
vi.mock('../../../server/utils/backups/package', () => mocks)
let root: string, server: Server, origin: string
beforeEach(async () => {
  vi.resetAllMocks()
  root = await mkdtemp(join(tmpdir(), 'pb-download-http-owned-'))
  vi.stubGlobal('defineEventHandler', defineEventHandler); vi.stubGlobal('createError', createError); vi.stubGlobal('getRouterParam', getRouterParam)
  const file = join(root, 'backup.tar.gz'); await writeFile(file, 'owned immutable bundle')
  mocks.getBackup.mockResolvedValue({id: 'fixture', type: 'full', status: 'ready', parent: null, included_tables: null})
  mocks.ensureBundle.mockResolvedValue(file)
  const {default: handler} = await import('../../../server/api/admin/backups/[id]/download.get')
  const app = createApp(), router = createRouter()
  router.get('/api/admin/backups/:id/download', handler)
  router.head('/api/admin/backups/:id/download', handler)
  // Independent stream-lifetime probe; generated bytes only, no configured DB.
  router.get('/slow', defineEventHandler(async event => {
    const release = await acquireSnapshotRead('slow')
    try {await sendBackupFile(event, join(root, 'large'), 'large.tar.gz', 32 * 1024 * 1024)} finally {release()}
  }))
  app.use(router)
  server = createServer(toNodeListener(app)); server.listen(0, '127.0.0.1'); await once(server, 'listening')
  origin = `http://127.0.0.1:${(server.address() as {port: number}).port}`
})
afterEach(async () => {server.closeAllConnections(); await new Promise<void>(resolve => server.close(() => resolve())); vi.unstubAllGlobals(); await rm(root, {recursive: true, force: true})})
describe('unified download through real H3/HTTP and filesystem streams', () => {
  it('streams one safe gzip attachment, actual length and private no-store; HEAD has no body', async () => {
    const response = await fetch(`${origin}/api/admin/backups/fixture/download`)
    expect(response.status).toBe(200)
    expect(response.headers.get('cache-control')).toBe('private, no-store')
    expect(response.headers.get('content-type')).toBe('application/gzip')
    expect(response.headers.get('content-disposition')).toBe('attachment; filename="pandablog-fixture.tar.gz"')
    const bytes = await response.text(); expect(bytes).toBe(await readFile(join(root, 'backup.tar.gz'), 'utf8'))
    expect(Number(response.headers.get('content-length'))).toBe(Buffer.byteLength(bytes))
    const head = await fetch(`${origin}/api/admin/backups/fixture/download`, {method: 'HEAD'})
    expect(head.status).toBe(200); expect(await head.text()).toBe('')
    await vi.waitFor(() => expect(snapshotHasReaders('fixture')).toBe(false))
  })
  it.each([null, {type: 'full', status: 'creating'}, {type: 'partial', status: 'ready'}, {type: 'future', status: 'ready'}, {type: 'full', status: 'ready', parent: 'base'}])('rejects missing/nonready/unsupported records %j without packaging', async record => {
    mocks.getBackup.mockResolvedValue(record)
    const response = await fetch(`${origin}/api/admin/backups/fixture/download`)
    expect(response.status).toBe(409); expect(response.headers.get('content-disposition')).toBeNull()
    expect(mocks.ensureBundle).not.toHaveBeenCalled()
    await response.body?.cancel()
  })
  it('auth precedes snapshot access; retired consolidation parameters fail explicitly', async () => {
    mocks.requireSuperadmin.mockRejectedValueOnce(createError({statusCode: 403}))
    expect((await fetch(`${origin}/api/admin/backups/fixture/download`)).status).toBe(403)
    expect(mocks.getBackup).not.toHaveBeenCalled()
    expect((await fetch(`${origin}/api/admin/backups/fixture/download?consolidate=0`)).status).toBe(400)
    expect(mocks.ensureBundle).not.toHaveBeenCalled()
  })
  it('holds its lease through real backpressure/disconnect and retains the source', async () => {
    await writeFile(join(root, 'large'), Buffer.alloc(32 * 1024 * 1024, 1))
    const request = get(`${origin}/slow`)
    const [response] = await once(request, 'response')
    response.pause()
    expect(snapshotHasReaders('slow')).toBe(true)
    expect(() => reserveSnapshotDeletion('slow')).toThrow(/readers/)
    response.destroy(); request.destroy()
    await vi.waitFor(() => expect(snapshotHasReaders('slow')).toBe(false), {timeout: 3000})
    expect((await readFile(join(root, 'large'))).length).toBe(32 * 1024 * 1024)
  })
})
