declare const __PB_MODULE_EDITOR__: boolean
declare const __PB_MODULE_LOGS__: boolean
declare const __PB_MODULE_LOGS_ACCESS__: boolean
declare const __PB_MODULE_LOGS_ACTIVITY__: boolean
declare const __PB_MODULE_LOGS_ERROR__: boolean
declare const __PB_MODULE_ANALYTICS__: boolean
declare const __PB_MODULE_ANALYTICS_GEOIP__: boolean
declare const __PB_MODULE_USERS__: boolean
declare const __PB_MODULE_USERS_MULTI_USER__: boolean
declare const __PB_MODULE_THEMES__: boolean
declare const __PB_MODULE_MFA__: boolean
declare const __PB_MODULE_SECURITY_ALERTS__: boolean
declare const __PB_MODULE_BACKUPS__: boolean

declare const __PB_BLOCK_ACCORDION_BLOCK__: boolean
declare const __PB_BLOCK_ANNOTATION_BLOCK__: boolean
declare const __PB_BLOCK_BLOCK_MATH__: boolean
declare const __PB_BLOCK_BLOCKQUOTE__: boolean
declare const __PB_BLOCK_CODE_BLOCK__: boolean
declare const __PB_BLOCK_COLUMNS_BLOCK__: boolean
declare const __PB_BLOCK_CUSTOM_HTML__: boolean
declare const __PB_BLOCK_DIFF_BLOCK__: boolean
declare const __PB_BLOCK_FILES_BLOCK__: boolean
declare const __PB_BLOCK_FOOTNOTES_BLOCK__: boolean
declare const __PB_BLOCK_HORIZONTAL_RULE__: boolean
declare const __PB_BLOCK_IMAGE__: boolean
declare const __PB_BLOCK_INLINE_MATH__: boolean
declare const __PB_BLOCK_MEDIA_TEXT__: boolean
declare const __PB_BLOCK_MERMAID__: boolean
declare const __PB_BLOCK_RELATED_POST__: boolean
declare const __PB_BLOCK_TABLE__: boolean
declare const __PB_BLOCK_TABS_BLOCK__: boolean
declare const __PB_BLOCK_VIDEO_EMBED__: boolean
