import { afterEach, describe, expect, it, vi } from 'vitest'
import { WriteBarrier } from '../../server/utils/maintenance'
import { StartupCoordinator } from '../../server/utils/startup'
import { scopedCredentials } from '../../server/utils/startup-config'
function deferred<T>() {
  let resolve!: (value: T) => void
  const promise = new Promise<T>(yes => {resolve = yes})
  return {promise, resolve}
}
function fixture() {
  const barrier = new WriteBarrier(), coordinator = new StartupCoordinator(barrier)
  const resources = {validate: vi.fn(), acquireWriter: vi.fn().mockResolvedValue(true), preserveFailure: vi.fn().mockResolvedValue(undefined), releaseWriter: vi.fn().mockResolvedValue(undefined), dispose: vi.fn().mockResolvedValue(undefined)}
  vi.spyOn(console, 'error').mockImplementation(() => {})
  return {barrier, coordinator, resources}
}
afterEach(() => {vi.restoreAllMocks(); vi.useRealTimers()})
describe('owned startup coordination and bounded shutdown', () => {
  it('single-flights ownership and private initialization, blocking background work until ready', async () => {
    const {barrier, coordinator, resources} = fixture(), pending = deferred<boolean>()
    resources.acquireWriter.mockReturnValue(pending.promise)
    const flight = coordinator.start(resources)
    expect(coordinator.start(resources)).toBe(flight)
    const boot = vi.fn(async () => {await barrier.run(async () => undefined, true)})
    const initialization = coordinator.initialize(boot)
    expect(coordinator.initialize(boot)).toBe(initialization)
    await expect(barrier.run(async () => undefined, true)).rejects.toMatchObject({statusCode: 503})
    expect(boot).not.toHaveBeenCalled()
    pending.resolve(true)
    expect(await initialization).toBe(true)
    expect(boot).toHaveBeenCalledOnce()
    expect(coordinator.status()).toEqual({state: 'ready', ready: true})
    await coordinator.stop()
    expect(resources.dispose).toHaveBeenCalledOnce()
    expect(resources.releaseWriter).toHaveBeenCalledOnce()
    await expect(barrier.run(async () => undefined)).rejects.toThrow()
  })
  it.each(['missing-config', 'ownership-rejection', 'recovery'] as const)('never initializes or releases a foreign receipt on %s', async reason => {
    const {coordinator, resources} = fixture()
    if (reason === 'missing-config') resources.validate.mockImplementation(() => {throw new Error('synthetic secret')})
    if (reason === 'ownership-rejection') resources.acquireWriter.mockRejectedValue(new Error('synthetic secret'))
    if (reason === 'recovery') resources.acquireWriter.mockResolvedValue(false)
    void coordinator.start(resources)
    const boot = vi.fn()
    expect(await coordinator.initialize(boot)).toBe(false)
    expect(boot).not.toHaveBeenCalled()
    expect(coordinator.status().ready).toBe(false)
    await coordinator.stop()
    expect(resources.releaseWriter).not.toHaveBeenCalled()
    expect(JSON.stringify(vi.mocked(console.error).mock.calls)).not.toContain('synthetic secret')
  })
  it('identifies an invalid scoped username before ownership or ROOT provisioning begins', async () => {
    const {coordinator, resources} = fixture()
    resources.validate.mockImplementation(() => {scopedCredentials({surrealAppUser: 'fixture-app', surrealAppPassword: 'must-not-leak'})})
    expect(await coordinator.start(resources)).toBe(false)
    const boot = vi.fn()
    expect(await coordinator.initialize(boot)).toBe(false)
    expect(coordinator.status()).toEqual({state: 'failed', ready: false, failure: {phase: 'ownership', category: 'invalid-scoped-username'}})
    expect(resources.acquireWriter).not.toHaveBeenCalled()
    expect(resources.preserveFailure).not.toHaveBeenCalled()
    expect(boot).not.toHaveBeenCalled()
    expect(JSON.stringify([coordinator.status(), vi.mocked(console.error).mock.calls])).not.toMatch(/fixture-app|must-not-leak/)
    await coordinator.stop()
  })
  it('preserves authority on partial boot failure, with no raw cause/SQL logging', async () => {
    const {coordinator, resources} = fixture()
    void coordinator.start(resources)
    expect(await coordinator.initialize(async () => {throw new Error('password SQL nested cause')})).toBe(false)
    expect(coordinator.status().state).toBe('failed')
    await coordinator.stop()
    expect(resources.preserveFailure).toHaveBeenCalledOnce()
    expect(resources.releaseWriter).not.toHaveBeenCalled()
    expect(JSON.stringify(vi.mocked(console.error).mock.calls)).not.toContain('password SQL')
  })
  it('reports sanitized handshake identity/stage rather than losing the initialization cause', async () => {
    const {coordinator, resources} = fixture()
    await coordinator.start(resources)
    const error = Object.assign(new Error('password SQL endpoint must-not-leak'), {data: {kind: 'database-handshake', scope: 'root', phase: 'authentication', cause: 'must-not-leak'}})
    expect(await coordinator.initialize(async () => {throw error})).toBe(false)
    expect(coordinator.status()).toEqual({state: 'failed', ready: false, failure: {phase: 'initialization', category: 'database-root-authentication-failed'}})
    expect(JSON.stringify(vi.mocked(console.error).mock.calls)).toContain('database-root-authentication-failed')
    expect(JSON.stringify([coordinator.status(), vi.mocked(console.error).mock.calls])).not.toContain('must-not-leak')
    await coordinator.stop()
    expect(resources.preserveFailure).toHaveBeenCalledOnce()
    expect(resources.releaseWriter).not.toHaveBeenCalled()
  })
  it('releases owned pre-mutation failures only after disposal, without persisting recovery authority', async () => {
    const {coordinator, resources, barrier} = fixture()
    const order: string[] = []
    resources.dispose.mockImplementation(async () => {order.push('dispose')})
    resources.releaseWriter.mockImplementation(async () => {order.push('release')})
    const proof = vi.fn().mockReturnValue(true)
    await coordinator.start({...resources, isPreMutationFailure: proof})
    expect(await coordinator.initialize(async () => {throw new Error('synthetic handshake failure')})).toBe(false)
    expect(order).toEqual(['dispose', 'release'])
    expect(coordinator.guidance()).toMatchObject({action: 'fix-config-and-restart', recoveryRequired: false})
    expect(resources.preserveFailure).not.toHaveBeenCalled()
    expect(barrier.status().closed).toBe(true) // failure never publishes readiness
    await coordinator.stop()
    expect(resources.dispose).toHaveBeenCalledOnce()
    expect(resources.releaseWriter).toHaveBeenCalledOnce()
  })
  it('preserves ownership if pre-mutation disposal fails', async () => {
    const {coordinator, resources} = fixture()
    resources.dispose.mockRejectedValue(new Error('synthetic disposal failure'))
    await coordinator.start({...resources, isPreMutationFailure: () => true})
    expect(await coordinator.initialize(async () => {throw new Error('synthetic handshake failure')})).toBe(false)
    expect(coordinator.guidance()).toMatchObject({action: 'run-recovery-assistant', recoveryRequired: true})
    expect(resources.releaseWriter).not.toHaveBeenCalled()
    expect(resources.preserveFailure).toHaveBeenCalledOnce()
    await coordinator.stop()
  })
  it('late pre-mutation disposal after its deadline cannot release the writer', async () => {
    vi.useFakeTimers()
    const {coordinator, resources} = fixture(), pending = deferred<undefined>()
    resources.dispose.mockReturnValue(pending.promise)
    await coordinator.start({...resources, isPreMutationFailure: () => true})
    const boot = coordinator.initialize(async () => {throw new Error('synthetic handshake failure')})
    await vi.advanceTimersByTimeAsync(5_001)
    expect(await boot).toBe(false)
    expect(resources.preserveFailure).toHaveBeenCalledOnce()
    pending.resolve(undefined)
    await Promise.resolve(); await Promise.resolve(); await Promise.resolve()
    expect(resources.releaseWriter).not.toHaveBeenCalled()
    await coordinator.stop()
  })
  it('does not release pre-mutation ownership if work is still active', async () => {
    const {coordinator, resources, barrier} = fixture()
    await coordinator.start({...resources, isPreMutationFailure: () => true})
    let release!: () => void
    expect(await coordinator.initialize(async () => {release = barrier.acquire(); throw new Error('synthetic handshake failure')})).toBe(false)
    expect(resources.releaseWriter).not.toHaveBeenCalled()
    expect(resources.preserveFailure).toHaveBeenCalledOnce()
    release()
    await coordinator.stop()
  })
  it('never echoes arbitrary metadata in startup diagnostics', async () => {
    const {coordinator, resources} = fixture()
    await coordinator.start(resources)
    expect(await coordinator.initialize(async () => {throw {data: {kind: 'database-handshake', scope: 'root', phase: 'password SQL must-not-leak'}}})).toBe(false)
    expect(coordinator.status().failure).toEqual({phase: 'initialization', category: 'initialization-failed'})
    expect(JSON.stringify([coordinator.status(), vi.mocked(console.error).mock.calls])).not.toContain('must-not-leak')
    await coordinator.stop()
  })
  it('explains persistent recovery even when the writer receipt has been removed', async () => {
    const {coordinator, resources} = fixture()
    resources.acquireWriter.mockResolvedValue(false)
    await coordinator.start(resources)
    const boot = vi.fn()
    expect(await coordinator.initialize(boot)).toBe(false)
    expect(boot).not.toHaveBeenCalled()
    expect(coordinator.status()).toEqual({state: 'recovery-required', ready: false, failure: {phase: 'recovery', category: 'offline-recovery-required'}})
    expect(JSON.stringify(vi.mocked(console.error).mock.calls)).toContain('removing only the writer lock cannot recover')
    await coordinator.stop()
  })
  it('close during acquisition prevents boot and safely releases only late owned acquisition', async () => {
    const {coordinator, resources} = fixture(), pending = deferred<boolean>()
    resources.acquireWriter.mockReturnValue(pending.promise)
    void coordinator.start(resources)
    const boot = vi.fn(), initializing = coordinator.initialize(boot)
    await vi.waitFor(() => expect(resources.acquireWriter).toHaveBeenCalledOnce())
    const closing = coordinator.stop()
    pending.resolve(true)
    await closing; await initializing
    expect(boot).not.toHaveBeenCalled()
    expect(resources.releaseWriter).toHaveBeenCalledOnce()
    expect(coordinator.status().ready).toBe(false)
  })
  it('late boot after bounded close cannot publish ready or remove recovery authority', async () => {
    vi.useFakeTimers()
    const {coordinator, resources, barrier} = fixture(), pending = deferred<undefined>()
    await coordinator.start(resources)
    const boot = coordinator.initialize(() => pending.promise)
    await Promise.resolve()
    const closing = coordinator.stop(10)
    await vi.advanceTimersByTimeAsync(11)
    await closing
    pending.resolve(undefined)
    await boot
    expect(coordinator.status()).toEqual({state: 'stopping', ready: false})
    expect(barrier.status().closed).toBe(true)
    expect(resources.releaseWriter).not.toHaveBeenCalled()
  })
  it('does not release if disposal exceeds the shutdown budget', async () => {
    vi.useFakeTimers()
    const {coordinator, resources} = fixture(), pending = deferred<undefined>()
    resources.dispose.mockReturnValue(pending.promise)
    await coordinator.start(resources); await coordinator.initialize(async () => {})
    const closing = coordinator.stop(10)
    await vi.advanceTimersByTimeAsync(11); await closing
    pending.resolve(undefined); await Promise.resolve(); await Promise.resolve()
    expect(resources.releaseWriter).not.toHaveBeenCalled()
  })
})
